@startuml containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Container diagram для Smart Home системы (To-Be - микросервисная архитектура)

Person(user, "Пользователь", "Житель дома")

System_Boundary(smartHomeSystem, "Smart Home System") {
    Container(apiGateway, "API Gateway", "Go", "Точка входа в систему, маршрутизация запросов к микросервисам")

    Container(telemetryService, "Telemetry Service", ".NET/C#", "Сбор и хранение телеметрических данных, статистика")

    Container(deviceService, "Device Service", ".NET/C#", "Управление устройствами и командами")

    Container(temperatureApi, "Temperature API", ".NET/C#", "Эмуляция физических датчиков температуры")
}

ContainerDb(database, "PostgreSQL", "PostgreSQL", "Хранит датчики, телеметрию, устройства и команды")

System_Ext(iotSensors, "IoT Temperature Sensors", "Физические датчики температуры в доме")

Rel(user, apiGateway, "Просматривает данные, управляет системой", "HTTPS/REST")

Rel(apiGateway, telemetryService, "Получает телеметрию", "HTTP/REST")
Rel(apiGateway, deviceService, "Управляет устройствами", "HTTP/REST")
Rel(apiGateway, temperatureApi, "Запрашивает температуру", "HTTP/REST")

Rel(telemetryService, database, "Читает/пишет телеметрию", "SQL/TCP")
Rel(telemetryService, temperatureApi, "Запрашивает показания", "HTTP/REST")

Rel(deviceService, database, "Читает/пишет устройства", "SQL/TCP")

Rel(temperatureApi, iotSensors, "Получает данные от датчиков", "HTTP/MQTT")

@enduml
